package com.xuanhe.prize.commons.db.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ViewGameProductNum implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_game_product_num.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_game_product_num.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_game_product_num.starttime
     *
     * @mbg.generated
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_game_product_num.endtime
     *
     * @mbg.generated
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_game_product_num.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_game_product_num.total
     *
     * @mbg.generated
     */
    private BigDecimal total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_game_product_num.hit
     *
     * @mbg.generated
     */
    private Long hit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table view_game_product_num
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_game_product_num.id
     *
     * @return the value of view_game_product_num.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_game_product_num.id
     *
     * @param id the value for view_game_product_num.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_game_product_num.title
     *
     * @return the value of view_game_product_num.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_game_product_num.title
     *
     * @param title the value for view_game_product_num.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_game_product_num.starttime
     *
     * @return the value of view_game_product_num.starttime
     *
     * @mbg.generated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_game_product_num.starttime
     *
     * @param starttime the value for view_game_product_num.starttime
     *
     * @mbg.generated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_game_product_num.endtime
     *
     * @return the value of view_game_product_num.endtime
     *
     * @mbg.generated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_game_product_num.endtime
     *
     * @param endtime the value for view_game_product_num.endtime
     *
     * @mbg.generated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_game_product_num.type
     *
     * @return the value of view_game_product_num.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_game_product_num.type
     *
     * @param type the value for view_game_product_num.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_game_product_num.total
     *
     * @return the value of view_game_product_num.total
     *
     * @mbg.generated
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_game_product_num.total
     *
     * @param total the value for view_game_product_num.total
     *
     * @mbg.generated
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_game_product_num.hit
     *
     * @return the value of view_game_product_num.hit
     *
     * @mbg.generated
     */
    public Long getHit() {
        return hit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_game_product_num.hit
     *
     * @param hit the value for view_game_product_num.hit
     *
     * @mbg.generated
     */
    public void setHit(Long hit) {
        this.hit = hit;
    }
}